# Import

In [21]:
import numpy as np

## array

In [22]:
arr=np.array([1,2,3,4,5])
type(arr)

numpy.ndarray

In [23]:
my_matrix=[[1,2,3],
            [1,2,3]]

np.array(my_matrix)

array([[1, 2, 3],
       [1, 2, 3]])

## zeros

In [24]:
np.zeros(3)

array([0., 0., 0.])

In [25]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## ones

In [26]:
np.ones(3)

array([1., 1., 1.])

In [27]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## eye

In [28]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## arange

In [29]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## linspace

In [31]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [32]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## random

### rand

In [33]:
np.random.rand(2)

array([0.41456807, 0.55888956])

In [34]:
np.random.rand(2,4)

array([[0.33604901, 0.12265739, 0.99360575, 0.56201731],
       [0.55033859, 0.08354501, 0.56471835, 0.67825749]])

### randn

In [35]:
np.random.randn(2)

array([-0.78010429, -0.8068887 ])

### randint

In [36]:
np.random.randint(1,100)

11

In [37]:
np.random.randint(1,100,10)

array([63, 14, 13, 13, 76, 71, 46, 10, 85, 93])

### normal

In [38]:
arr = np.random.normal(loc=0, scale=1, size=50)
arr

array([ 1.02726508e+00,  1.98416493e+00, -1.33965766e+00, -1.02882678e-01,
       -5.32585922e-01, -9.44302173e-01, -1.37833907e+00, -3.34042570e-01,
       -7.84493648e-01, -8.38613436e-02, -9.67110107e-01,  4.77855976e-01,
        1.53431778e+00, -2.22167530e-01, -1.29421577e+00, -1.47107213e-01,
        1.39695947e+00, -3.04990187e-01,  8.82884501e-02, -3.49117822e-01,
       -1.12429879e+00, -1.93636680e-01,  1.97946175e+00, -1.06066153e+00,
        1.48810878e+00,  1.08587076e-01,  6.42371516e-01,  5.90707476e-01,
       -1.12910054e+00,  9.09776607e-01,  1.08231759e+00,  1.72083809e+00,
       -1.24204881e+00, -5.41427171e-01,  4.58594057e-01, -1.15052262e+00,
       -1.28389199e+00,  1.05345244e+00,  5.13648171e-01, -1.19907582e+00,
       -3.29091481e-02,  4.39850667e-01,  5.92660239e-01,  1.45639780e-01,
        1.92692911e-03, -6.11214820e-01,  3.87012832e-01, -3.92042843e-02,
       -1.00438800e+00, -1.17798554e+00])

### choice

In [39]:
arr = np.array([1, 2, 3, 4])
arr_sample = np.random.choice(arr, size=2)
print(arr_sample)

[4 3]


## shape

In [40]:
arr=np.array([[10,93,45,67],[10,300,45,67]])
arr.shape

(2, 4)

## reshape

In [41]:
arr = np.arange(25)
print(f'befor reshape \n {arr}')
arr_reshape = arr.reshape(5,5)
print(f'after reshape \n {arr_reshape}')

befor reshape 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
after reshape 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## Concatenate two arrays

In [42]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4]


## Split an array into multiple sub-arrays

In [43]:
arr = np.array([1, 2, 3, 4])
arr_split = np.split(arr, 2)
print(arr_split)

[array([1, 2]), array([3, 4])]


## max

In [44]:
arr2=np.array([10,93,45,67])
arr2.max()

93

## min

In [45]:
arr2=np.array([10,93,45,67])
arr2.min()

10

## argmax

In [46]:
arr2=np.array([[10,93,45,67],[10,300,45,67]])
arr2.argmax()

5

## Index

### Vector Index

In [47]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr[-1]

10

In [49]:
arr[0:4]

array([0, 1, 2, 3])

### Matrix Index

In [50]:
matrix=np.array([[1,2,3],
                [4,5,6],
                [6,7,8]])

In [51]:
matrix[1:3 ,0:2]

array([[4, 5],
       [6, 7]])

## copy
important

In [52]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
new_arr=arr[0:4]
new_arr

array([0, 1, 2, 3])

In [54]:
new_arr[:]=100
new_arr

array([100, 100, 100, 100])

In [55]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

## Broadcasting

In [56]:
y=np.array([1,2,3,4,5])
scaler=6
y + scaler

array([ 7,  8,  9, 10, 11])

In [57]:
arr1=np.array([[1,2,3],[1,2,3]])
arr2=np.array([1,2,3])
# arr2=np.array([[1,2,3],[1,2,3]])
arr1 + arr2

array([[2, 4, 6],
       [2, 4, 6]])

In [58]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1], [2], [3]])
arr_broadcast = arr1 + arr2
print(arr_broadcast)


[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [59]:
arr1=np.array([[1,2,3],[1,2,3]])
arr2=np.array([1,2,3])
arr = np.add(arr1, arr2)
arr

array([[2, 4, 6],
       [2, 4, 6]])

In [60]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
arr = np.subtract(arr1, arr2)
print(arr)


[-2 -2]


In [61]:
A=np.array([
    [1,2],
    [4,5]])

B=np.array([
    [1,2],
    [6,5]])

In [62]:
A + B

array([[ 2,  4],
       [10, 10]])

In [63]:
A - B

array([[ 0,  0],
       [-2,  0]])

## exponential

In [64]:
arr = np.array([1, 2, 3])
arr_exp = np.exp(arr)
print(arr_exp)

[ 2.71828183  7.3890561  20.08553692]


#### Elementwise

In [65]:
A * B  

array([[ 1,  4],
       [24, 25]])

In [66]:
arr = np.multiply(A, B)
arr

array([[ 1,  4],
       [24, 25]])

#### dot product

In [67]:
A.dot(B)  

array([[13, 12],
       [34, 33]])

In [68]:
arr = np.dot(A, B)
arr

array([[13, 12],
       [34, 33]])

## Transpose

In [69]:
arr=np.array([
    [1,2],
    [3,4],
    [5,6],
])
print(f'befor transpose \n {arr}')
arr_transpose = arr.T
print(f'after transpose \n {arr_transpose}')

befor transpose 
 [[1 2]
 [3 4]
 [5 6]]
after transpose 
 [[1 3 5]
 [2 4 6]]


## mean

In [70]:
A=np.array([1,2,3,4,5,6,7])
print(np.mean(A))

4.0


## median

In [71]:
A=np.array([1,2,4,5,6,7,2,3,4,5,6,7])
print(np.median(A))

4.5


## mode

In [72]:
from statistics import mode

In [73]:
def zyad_mode(lis):
    """
    This function takes a list and returns the mode, if there is more than one adds them to a list and shows all.
    """
    #Checking for the tank is empty or not.
    if len(lis) == 0:
        return 'The tank must not be empty.'
    else:
        # Create a Counter object from the list
        from typing import Counter
        # Get the most common elements from the Counter object and get the number of times each element appears
        pairs = Counter(iter(lis)).most_common()
        # Get the number of times the most common element(s) appear
        times_repeated = pairs[0][1]
        # Get the most repeated element(s)
        most_repeated = []
        for i in pairs:
            if i[1] == times_repeated:
                most_repeated.append(i[0])
        # If only one element is the most common, return it
        if len(most_repeated) == 1:
            return most_repeated[0]
        # If more than one element is the most common, return a list of them
        else:
            return most_repeated

In [74]:
A=np.array([1,1,1,2,2,2,3,3,3,4,5,6,8,7,9,9,9])
print(mode(A))
print(zyad_mode(A))

1
[1, 2, 3, 9]


## mean for columns or row

In [75]:
A=np.array([[1,2,3,4,5,6,7],
            [1,2,3,4,5,6,7]])
column_mean = np.mean(A,axis=0)
row_mean = np.mean(A,axis=1)
print('column_mean',column_mean)
print('row_mean',row_mean)

column_mean [1. 2. 3. 4. 5. 6. 7.]
row_mean [4. 4.]


## Variance

In [76]:
v=np.array([1,2,3,4,5,6])
np.var(v)

2.9166666666666665

### Variance for columns or row

In [77]:
v=np.array([[1,2,3,4,5,6],
            [1,2,3,4,5,6]])

column_variance=np.var(v,axis=0)
row_variance=np.var(v,axis=1)

print('column_variance',column_variance)
print('row_variance',row_variance)

column_variance [0. 0. 0. 0. 0. 0.]
row_variance [2.91666667 2.91666667]


## Standard Deviation

In [78]:
v=np.array([1,2,3,4,5,6])
np.std(v)

1.707825127659933

### Standard Deviation for columns or row

In [79]:
v=np.array([[1,2,3,4,5,6],
            [1,2,3,4,5,6]])

column_std=np.std(v,axis=0)
row_std=np.std(v,axis=1)

print('column_std',column_std)
print('row_std',row_std)

column_std [0. 0. 0. 0. 0. 0.]
row_std [1.70782513 1.70782513]


## Write a function stats() that takes any sequence of numbers and giveback
## its mean, variance and std.

In [80]:
def stats(variables,col):

    matrix=np.array(variables)
    if col== 'col':
        axis=0
    elif col== 'row':
        axis=1

    else:
        print('error')

    if len(matrix.shape)==1:

        mean=np.mean(matrix)
        var=np.var(matrix)
        std=np.std(matrix)
    else:
        mean=np.mean(matrix,axis=axis)
        var=np.var(matrix,axis=axis)
        std=np.std(matrix,axis=axis)
    return [mean,var,std]

In [81]:
vector =np.array([1,2,3,4,5,6])
matrix=np.array([[1,2,3,4,5,6],
                [1,2,3,4,5,6]])

In [82]:
print(stats(vector,'col'))

print(stats(matrix,'col'))

print(stats(matrix,'row'))

[3.5, 2.9166666666666665, 1.707825127659933]
[array([1., 2., 3., 4., 5., 6.]), array([0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0.])]
[array([3.5, 3.5]), array([2.91666667, 2.91666667]), array([1.70782513, 1.70782513])]


## Covariance

In [83]:
x=np.array([1,2,3,4,5,6,7,8,9])
y=np.array([9,8,7,6,5,4,3,2,1])

res_cov=np.cov(x,y)

print(res_cov)
#where the diagonal elements will represent the variance of x and y,
#respectively, and the off-diagonal elements will represent the covariance between them

[[ 7.5 -7.5]
 [-7.5  7.5]]


In [84]:
#To find the covariance between two arrays. Access it by[0,1]

res_cov=np.cov(x,y)[0,1]

print(res_cov)

-7.5


## correlation

In [85]:
x=np.array([1,2,3,4,5,6,7,8,9])
y=np.array([9,8,7,6,5,4,3,2,1])

res_cor=np.corrcoef(x,y)

print(res_cor)
#where the diagonal elements will be 1, and the off-diagonal elements will represent the correlation coefficient between them.

[[ 1. -1.]
 [-1.  1.]]


In [86]:
#To find the correlation between two arrays. Access it by[0,1]

res_cor=np.corrcoef(x,y)[0,1]

print(res_cor)

-1.0


## nth percentile

In [87]:
arr = np.array([1, 2, 3, 4])
arr_percentile = np.percentile(arr, 50)
print(arr_percentile)

2.5


## Linear Algebra

### (multiplicative) inverse of a matrix.

In [88]:
arr = np.array([[1, 2], [3, 4]])
arr_inv = np.linalg.inv(arr)
print(arr_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


### eigenvalues and right eigenvectors of a square array

In [89]:
arr = np.array([[1, 2], [3, 4]])
eigvals, eigvecs = np.linalg.eig(arr)
print('eigvals:',eigvals)
print('\neigvecs: \n',eigvecs)


eigvals: [-0.37228132  5.37228132]

eigvecs: 
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


### Singular Value Decomposition

In [90]:
arr = np.array([[1, 2], [3, 4]])
U, s, V = np.linalg.svd(arr)
print('U: \n',U)
print('\ns: ',s)
print('\nV: \n',V)


U: 
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]

s:  [5.4649857  0.36596619]

V: 
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


### matrix or vector norm

In [91]:
arr = np.array([1, 2, 3, 4])
arr_norm = np.linalg.norm(arr)
arr_norm

5.477225575051661